from __future__ import annotations

import json
from pathlib import Path

from novelos_mcp.archetype_recommendation import GENRE_TEMPERAMENT_MAP, TONE_TEMPERAMENT_MAP
from novelos_mcp.system_archetypes import load_system_archetypes_config


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "mcp" / "novelos" / "src" / "novelos_mcp" / "ui" / "project-wizard-data.js"


def build() -> str:
    archetypes = load_system_archetypes_config(ROOT / "config" / "system_archetypes.json")
    payload = {
        "system_archetypes": [
            {
                "display_name": item["display_name"],
                "profile_version_id": f"creator-profile-version:{item['id']}:1",
                "revision": item["revision"],
                "subject_hash": item["subject_hash"],
                "constraint_ref": f"novelos://creator-signature/{item['id']}/1/{item['subject_hash']}",
                "signature": item["signature"],
                "reader_promise": item["reader_promise"],
                "genre_tags": item["genre_tags"],
                "temperament_tags": item["temperament_tags"],
            }
            for item in archetypes
        ],
        "recommendation_rules": {
            "genre_temperaments": GENRE_TEMPERAMENT_MAP,
            "tone_temperaments": TONE_TEMPERAMENT_MAP,
        },
    }
    serialized = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return "// Generated by scripts/build_project_wizard_data.py. Do not edit manually.\nwindow.NOVELOS_WIZARD_DATA = " + serialized + ";\n"


def main() -> None:
    OUTPUT.write_text(build(), encoding="utf-8")


if __name__ == "__main__":
    main()
